### ISSUE TITLE
Enable docker buildkit

### ISSUE THREAD

**Issue by shavo007** [seek-oss/docker-ecr-cache-buildkite-plugin#12]
This is  a feature request

Enable buildkit to improve performance

https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds

**Comment by 72636c** [comment]
I haven't looked into BuildKit much, but this seems trivial to implement here and in https://github.com/seek-oss/docker-ecr-publish-buildkite-plugin. Do you mind raising an issue for the main Docker plugin https://github.com/buildkite-plugins/docker-buildkite-plugin to see what they say?

**Comment by shavo007** [comment]
yep, @72636c  can do. i just need some kind of env variable and a flag to enable if you like.

**Comment by shavo007** [comment]
this is only when building FYI

**Comment by shavo007** [comment]
i just use env variable in my step

```
    env:
      DOCKER_BUILDKIT: 1  
```

**Comment by 72636c** [comment]
Sorry for missing your comment, how did it go? I was planning to document this if it's a noticeable improvement.

**Comment by TSMMark** [comment]
Any updates on whether or not this has any noticeable impact?

**Comment by 72636c** [comment]
You can use the DOCKER_BUILDKIT environment variable, and we automatically set it for e.g. [Docker Build secrets](https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin#specifying-secrets). Feel free to open a new issue if something isn't working as expected.
