### ISSUE TITLE
Expired images cause build failure

### ISSUE THREAD

**Issue by EvilPuppetMaster** [seek-oss/docker-ecr-cache-buildkite-plugin#31]
We've run into an issue where cached images that have expired due to this max_age setting cause a buildkite failure, rather than just rebuilding the image:
https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin/blob/d2a4b4763f2fe9c01a79eab10633bddcbc8e4f4c/hooks/lib/ecr-registry-provider.bash#L78

The error is:

```
manifest for XXX not found: manifest unknown: Requested image not found
```

**Comment by EvilPuppetMaster** [comment]
Sorry, need to add some more context... we have a step that builds a base image that uses the ECR cache. We have a subsequent step that uses that base image.

In the case that the cached version has expired, the step that builds the base image runs and succeeds but does NOT recreate the cached image. So the subsequent step that attempts to use it fails.

**Comment by EvilPuppetMaster** [comment]
I can link you to a build that shows this in action, message me on Slack.

**Comment by 72636c** [comment]
Do you know if it's possible to cheaply recreate an image?

My recommendation would be to use the plugin on each step that relies on the cached image.

**Comment by 72636c** [comment]
Feel free to reopen if you have more details.
