### ISSUE TITLE
BYO  ecr repo

### ISSUE THREAD

**Issue by shavo007** [seek-oss/docker-ecr-cache-buildkite-plugin#8]
# Feature request 

it would be nice to pass in your own ecr repo rather than the plugin create it for you.

also, i see that the repo created has no lifecycle rules. As i am using this to cache node modules, i would like to keep image count less than x

Cheers,
Shane.

**Comment by 72636c** [comment]
Just curious, how would your BYO repo differ from one created via plugin? The intent is for you to worry less about the (Docker, ECR, etc.) details 🙂

Good catch on the lifecycle policy. Would something simple like this meet your needs?

1. Keep image tagged `latest`
1. Keep 20 other (tagged) images

**Comment by shavo007** [comment]
No difference @72636c , i just might want to be in control of it myself. And where the docker images are published. 

I only use the plugin for caching node_modules, not as release candidates.

So i would like to either:
1)BYO my repo with my own config and specify it as a field in the plugin
2) Let the plugin create the repo but i can specify lifecycle rules. As i said, my docker images are only for caching purposes. So if there was a field and i could pass in how many images i want to preserve. Otherwise, in the long run this will cost alot of money!

**Comment by 72636c** [comment]
See #9. The plugin will continually apply its own lifecycle policy so you can't really self-manage the repository, but I hope a reasonable default will suffice. I'm a bit reluctant to add more knobs here as it strays from the original intent.

> I only use the plugin for caching node_modules, not as release candidates.

This is the intended purpose. Final application images would be better handled by something like the [Docker ECR Publish plugin](https://github.com/seek-oss/docker-ecr-publish-buildkite-plugin).

**Comment by shavo007** [comment]
@72636c  awesome work mate. really like this.
